### ISSUE TITLE
关于ac_id

### ISSUE THREAD

**Issue by NB-wo** [Tony15246/buaa_wifi_login#1]
您好，我想知道你是怎么发现这个acid的值的？我在工位的话用1和62貌似都不行（login_ok但是没法上网）

**Comment by Tony15246** [comment]
我是使用控制台查看网络请求看到的，这个ac_id的作用是什么，背后是什么原理其实我也不是很清楚😂

我写这个脚本的时候其实就是照着学长的代码，再用控制台抓包网络请求的负载，把各种和学长代码里不一样的参数值改成我本地环境下能请求成功的参数值

![image](https://github.com/user-attachments/assets/7cf9432c-8254-4075-8c1b-6f5f05adc846)

其实gw.buaa.edu.cn的路由里也能直接看到，比如说我打开gw.buaa.edu.cn的时候看到的路由就是这样的`https://gw.buaa.edu.cn/srun_portal_pc?ac_id=62&theme=buaa`

**Comment by NB-wo** [comment]
> 我是使用控制台查看网络请求看到的，这个ac_id的作用是什么，背后是什么原理其实我也不是很清楚😂
> 
> 我写这个脚本的时候其实就是照着学长的代码，再用控制台抓包网络请求的负载，把各种和学长代码里不一样的参数值改成我本地环境下能请求成功的参数值
> 
> ![image](https://private-user-images.githubusercontent.com/94174703/369362154-7cf9432c-8254-4075-8c1b-6f5f05adc846.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjgzNzcsIm5iZiI6MTcyNjgyODA3NywicGF0aCI6Ii85NDE3NDcwMy8zNjkzNjIxNTQtN2NmOTQzMmMtODI1NC00MDc1LThjMWItNmY1ZjA1YWRjODQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEwMjc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYmY0YjQzMzUzMmVkMDA5ZjY5ZTNiZTA3NzQzMjAyMGE4Zjk1YzNlOWQ0NDQ0Mzc0NjEwOWFjZDlhOGE4NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4BU37dBOhTGseP9K1LWihYev3KjtmveRtTNxCaAz0pY)
> 
> 其实gw.buaa.edu.cn的路由里也能直接看到，比如说我打开gw.buaa.edu.cn的时候看到的路由就是这样的`https://gw.buaa.edu.cn/srun_portal_pc?ac_id=62&theme=buaa`

谢谢答复，acid可能是按区域分的
